language: node_js
node_js:
  - 10.16.3
cache:
  directories:
    - "node_modules"
script:
  - npm test
env:
  global:
    - export NODE_ENV=test
services: 
  - postgresql
before_script:
  - npm install
  - psql -c 'create database libera_test_db; ' -U postgres